import { EncounterCategory } from '../generated/prisma'

export const encounterCategories: EncounterCategory[] = [
  'UAP_LUMINOUS_ORBS',
  'UAP_DISC',
  'UAP_TRIANGLE',
  'UAP_CYLINDER',
  'UAP_SPHERE',
  'UAP_TRANS_MEDIUM',
  'UAP_FORMATION_SWARM',
  'CE_1',
  'CE_2',
  'CE_3',
  'CE_4_ABDUCTION',
  'CE_5_INITIATED_CONTACT',
  'CE_6_INJURY',
  'CE_7_LONG_TERM_CONTACT',
  'ENTITY_ENCOUNTER',
  'ABDUCTION_SCENARIO',
  'POLTERGEIST_ACTIVITY',
  'PORTAL_DIMENSIONAL',
  'CATTLE_MUTILATION',
  'MEN_IN_BLACK',
  'MISSING_TIME',
  'PSYCHIC_EFFECTS',
  'TRACE_EVIDENCE',
  'EM_INTERFERENCE',
  'RADIATION_EFFECTS',
  'WEATHER_DISTURBANCE',
  'OTHER',
]

export const encounterTags = [
  { id: 'UAP_LUMINOUS_ORBS', label: 'UAP Luminous Orbs' },
  { id: 'UAP_DISC', label: 'UAP Disc' },
  { id: 'UAP_TRIANGLE', label: 'UAP Triangle' },
  { id: 'UAP_CYLINDER', label: 'UAP Cylinder' },
  { id: 'UAP_SPHERE', label: 'UAP Sphere' },
  { id: 'UAP_TRANS_MEDIUM', label: 'UAP Trans Medium' },
  { id: 'UAP_FORMATION_SWARM', label: 'UAP Formation Swarm' },
  { id: 'CE_1', label: 'CE 1: Abduction' },
  { id: 'CE_2', label: 'CE 2: Abduction' },
  { id: 'CE_3', label: 'CE 3: Contact' },
  { id: 'CE_4_ABDUCTION', label: 'CE 4: Abduction' },
  { id: 'CE_5_INITIATED_CONTACT', label: 'CE 5: Initiated Contact' },
  { id: 'CE_6_INJURY', label: 'CE 6: Injury' },
  { id: 'CE_7_LONG_TERM_CONTACT', label: 'CE 7: Long Term Contact' },
  { id: 'ENTITY_ENCOUNTER', label: 'Entity Encounter' },
  { id: 'ABDUCTION_SCENARIO', label: 'Abduction Scenario' },
  { id: 'POLTERGEIST_ACTIVITY', label: 'Poltergeist Activity' },
  { id: 'PORTAL_DIMENSIONAL', label: 'Portal Dimensional' },
  { id: 'CATTLE_MUTILATION', label: 'Cattle Mutilation' },
  { id: 'MEN_IN_BLACK', label: 'Men in Black' },
  { id: 'MISSING_TIME', label: 'Missing Time' },
  { id: 'PSYCHIC_EFFECTS', label: 'Psychic Effects' },
  { id: 'TRACE_EVIDENCE', label: 'Trace Evidence' },
  { id: 'EM_INTERFERENCE', label: 'Electromagnetic Interference' },
  { id: 'RADIATION_EFFECTS', label: 'Radiation Effects' },
  { id: 'WEATHER_DISTURBANCE', label: 'Weather Disturbance' },
  { id: 'OTHER', label: 'Other' },
]
